/**
 * @typedef {import("../types.js").Item} Item
 */

/** @type {{ [id: number]: Item}} */
export const itemSourceDatabase = {
  22531: {
    source: "Crafting",
    phase: 1,
    slot: "wrist",
  },
  22534: {
    source: "Crafting",
    phase: 1,
    slot: "wrist",
  },
  22537: {
    source: "Crafting",
    phase: 1,
    slot: "ring",
  },
  22561: {
    source: "Crafting",
    phase: 1,
    slot: "mainHand",
  },
  24003: {
    source: "Crafting",
    phase: 1,
    slot: "chest",
  },
  24274: {
    source: "Crafting",
    phase: 1,
    slot: "legs",
  },
  24276: {
    source: "Crafting",
    phase: 1,
    slot: "legs",
  },
  25643: {
    quest: 9852,
    source: "Quests",
    phase: 1,
    slot: "relic",
  },
  28272: {
    source: "Crafting",
    phase: 1,
    slot: "hands",
  },
  28273: {
    source: "Crafting",
    phase: 1,
    slot: "hands",
  },
  28280: {
    source: "Crafting",
    phase: 1,
    slot: "feet",
  },
  28281: {
    source: "Crafting",
    phase: 1,
    slot: "mainHand",
  },
  28886: {
    source: "Reputation",
    faction: "The Aldor",
    phase: 1,
    slot: "shoulders",
  },
  28887: {
    source: "Reputation",
    faction: "The Aldor",
    phase: 1,
    slot: "shoulders",
  },
  29189: {
    source: "Reputation",
    faction: "Honor Hold",
    phase: 1,
    slot: "head",
  },
  29191: {
    source: "Reputation",
    faction: "The Sha'tar",
    phase: 1,
    slot: "head",
  },
  29309: {
    source: "Reputation",
    faction: "Scale of the Sands",
    phase: 1,
    slot: "ring",
  },
  29370: {
    source: "Badges of Justice",
    cost: 41,
    phase: 1,
    slot: "trinket",
  },
  29376: {
    cost: 41,
    source: "Badges of Justice",
    phase: 1,
    slot: "trinket",
  },
  30038: {
    source: "Crafting",
    phase: 1,
    slot: "waist",
  },
  30868: {
    source: "Instance",
    instance: "Hyjal Summit",
    boss: "Rage Winterchill",
    phase: 1,
    slot: "wrist",
  },
  30911: {
    source: "Instance",
    instance: "Hyjal Summit",
    boss: "Archimonde",
    phase: 1,
    slot: "offHand",
  },
  31037: {
    subItem: 31096,
    source: "Instance",
    instance: "Hyjal Summit",
    boss: "Archimonde",
    phase: 1,
    slot: "head",
  },
  31041: {
    subItem: 31090,
    source: "Instance",
    instance: "Black Temple",
    boss: "Illidan Stormrage",
    phase: 1,
    slot: "chest",
  },
  31061: {
    subItem: 31092,
    source: "Instance",
    instance: "Hyjal Summit",
    boss: "Azgalor",
    phase: 1,
    slot: "hands",
  },
  31064: {
    subItem: 31097,
    source: "Instance",
    instance: "Hyjal Summit",
    boss: "Archimonde",
    phase: 1,
    slot: "head",
  },
  31065: {
    subItem: 31089,
    source: "Instance",
    instance: "Black Temple",
    boss: "Illidan Stormrage",
    phase: 1,
    slot: "chest",
  },
  31070: {
    subItem: 31101,
    source: "Instance",
    instance: "Black Temple",
    boss: "Mother Shahraz",
    phase: 1,
    slot: "shoulders",
  },
  31856: {
    quest: 10938,
    source: "Quests",
    phase: 1,
    slot: "trinket",
  },
  32271: {
    source: "Instance",
    instance: "Black Temple",
    boss: "Shade of Akama",
    phase: 1,
    slot: "legs",
  },
  32328: {
    source: "Instance",
    instance: "Black Temple",
    boss: "Teron Gorefiend",
    phase: 1,
    slot: "hands",
  },
  32483: {
    source: "Instance",
    instance: "Black Temple",
    boss: "Illidan Stormrage",
    phase: 1,
    slot: "trinket",
  },
  32496: {
    source: "Instance",
    instance: "Black Temple",
    boss: "Illidan Stormrage",
    phase: 1,
    slot: "trinket",
  },
  32524: {
    source: "Instance",
    instance: "Black Temple",
    boss: "Illidan Stormrage",
    phase: 1,
    slot: "back",
  },
  32527: {
    source: "Instance",
    instance: "Black Temple",
    phase: 1,
    slot: "ring",
  },
  32528: {
    source: "Instance",
    instance: "Black Temple",
    phase: 1,
    slot: "ring",
  },
  32590: {
    source: "Instance",
    instance: "Hyjal Summit",
    phase: 1,
    slot: "back",
  },
  32609: {
    source: "Instance",
    instance: "Hyjal Summit",
    phase: 1,
    slot: "feet",
  },
  33150: {
    source: "Crafting",
    phase: 1,
    slot: "back",
  },
  33192: {
    source: "Badges of Justice",
    cost: 25,
    phase: 1,
    slot: "wand",
  },
  33281: {
    source: "Instance",
    instance: "Zul'Aman",
    boss: "Akil'zon",
    phase: 1,
    slot: "neck",
  },
  33334: {
    source: "Badges of Justice",
    cost: 35,
    phase: 1,
    slot: "offHand",
  },
  33468: {
    source: "Instance",
    instance: "Zul'Aman",
    boss: "Zul'jin",
    phase: 1,
    slot: "mainHand",
  },
  33483: {
    source: "Instance",
    instance: "Zul'Aman",
    phase: 1,
    slot: "waist",
  },
  33497: {
    source: "Instance",
    instance: "Zul'Aman",
    phase: 1,
    slot: "ring",
  },
  33829: {
    source: "Instance",
    instance: "Zul'Aman",
    boss: "Hex Lord Malacrass",
    phase: 1,
    slot: "trinket",
  },
  34170: {
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "Kalecgos",
    phase: 1,
    slot: "legs",
  },
  34176: {
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "Brutallus",
    phase: 1,
    slot: "mainHand",
  },
  34179: {
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "Brutallus",
    phase: 1,
    slot: "offHand",
  },
  34181: {
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "Brutallus",
    phase: 1,
    slot: "legs",
  },
  34199: {
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "Lady Sacrolash",
    phase: 1,
    slot: "mainHand",
  },
  34204: {
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "Lady Sacrolash",
    phase: 1,
    slot: "neck",
  },
  34206: {
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "Lady Sacrolash",
    phase: 1,
    slot: "offHand",
  },
  34209: {
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "Lady Sacrolash",
    phase: 1,
    slot: "shoulders",
  },
  34210: {
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "Lady Sacrolash",
    phase: 1,
    slot: "shoulders",
  },
  34212: {
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "M'uru",
    phase: 1,
    slot: "chest",
  },
  34233: {
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "M'uru",
    phase: 1,
    slot: "chest",
  },
  34242: {
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "Kil'jaeden",
    phase: 1,
    slot: "back",
  },
  34245: {
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "Kil'jaeden",
    phase: 1,
    slot: "head",
  },
  34335: {
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "Kil'jaeden",
    phase: 1,
    slot: "mainHand",
  },
  34336: {
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "Kil'jaeden",
    phase: 1,
    slot: "mainHand",
  },
  34339: {
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "Kil'jaeden",
    phase: 1,
    slot: "head",
  },
  34342: {
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "Kil'jaeden",
    phase: 1,
    slot: "hands",
  },
  34347: {
    source: "Instance",
    instance: "Sunwell Plateau",
    phase: 1,
    slot: "wand",
  },
  34384: {
    subItem: 34169,
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "Kalecgos",
    phase: 1,
    slot: "legs",
  },
  34386: {
    subItem: 34170,
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "Kalecgos",
    phase: 1,
    slot: "legs",
  },
  34434: {
    subItem: 34848,
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "Kalecgos",
    phase: 1,
    slot: "wrist",
  },
  34445: {
    subItem: 34852,
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "Kalecgos",
    phase: 1,
    slot: "wrist",
  },
  34554: {
    subItem: 34855,
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "Brutallus",
    phase: 1,
    slot: "waist",
  },
  34563: {
    subItem: 34856,
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "Felmyst",
    phase: 1,
    slot: "feet",
  },
  34571: {
    subItem: 34858,
    source: "Instance",
    instance: "Sunwell Plateau",
    boss: "Felmyst",
    phase: 1,
    slot: "feet",
  },
  34895: {
    source: "Badges of Justice",
    cost: 150,
    phase: 1,
    slot: "mainHand",
  },
  35431: {
    source: "Crafting",
    phase: 1,
    slot: "chest",
  },
};
