/**
 * @typedef {import("../types.js").Item} Item
 */

/** @type {{ [id: number | string]: Item}} */
export const itemSourceDatabase = {
  21869: {
    source: "Crafting",
    phase: 1,
    slot: "shoulders",
  },
  21870: {
    source: "Crafting",
    phase: 1,
    slot: "feet",
  },
  21871: {
    source: "Crafting",
    phase: 1,
    slot: "chest",
  },
  22531: {
    source: "Enchanting",
    phase: 1,
    slot: "wrist",
  },
  22534: {
    source: "Enchanting",
    phase: 1,
    slot: "wrist",
  },
  22537: {
    source: "Enchanting",
    phase: 1,
    slot: "ring",
  },
  22561: {
    source: "Enchanting",
    phase: 1,
    slot: "mainHand",
  },
  24003: {
    source: "Enchanting",
    phase: 1,
    slot: "chest",
  },
  24250: {
    source: "Crafting",
    phase: 1,
    slot: "wrist",
  },
  24262: {
    source: "Crafting",
    phase: 1,
    slot: "legs",
  },
  24264: {
    source: "Crafting",
    phase: 1,
    slot: "head",
  },
  24266: {
    source: "Crafting",
    phase: 1,
    slot: "head",
  },
  24273: {
    source: "Crafting",
    phase: 1,
    slot: "legs",
  },
  24274: {
    source: "Crafting",
    phase: 1,
    slot: "legs",
  },
  24275: {
    source: "Crafting",
    phase: 1,
    slot: "legs",
  },
  24276: {
    source: "Crafting",
    phase: 1,
    slot: "legs",
  },
  "24692_9": {
    source: "Auction House",
    phase: 1,
    slot: "wrist",
  },
  "25295_9": {
    source: "Auction House",
    phase: 1,
    slot: "wand",
  },
  27886: {
    source: "Shadow Labyrinth",
    boss: "Ambassador Hellmaw",
    phase: 1,
    slot: "relic",
  },
  28272: {
    source: "Enchanting",
    phase: 1,
    slot: "hands",
  },
  28273: {
    source: "Enchanting",
    phase: 1,
    slot: "hands",
  },
  28280: {
    source: "Enchanting",
    phase: 1,
    slot: "feet",
  },
  28281: {
    source: "Enchanting",
    phase: 1,
    slot: "mainHand",
  },
  28507: {
    source: "Karazhan",
    boss: "Attumen the Huntsman",
    phase: 1,
    slot: "hands",
  },
  28511: {
    source: "Karazhan",
    boss: "Maiden of Virtue",
    phase: 1,
    slot: "wrist",
  },
  28515: {
    source: "Karazhan",
    boss: "Maiden of Virtue",
    phase: 1,
    slot: "wrist",
  },
  28521: {
    source: "Karazhan",
    boss: "Maiden of Virtue",
    phase: 1,
    slot: "hands",
  },
  28555: {
    source: "PVP",
    phase: 1,
    slot: "ring",
  },
  28570: {
    source: "Karazhan",
    boss: "Moroes",
    phase: 1,
    slot: "back",
  },
  28591: {
    source: "Karazhan",
    boss: "Opera",
    phase: 1,
    slot: "legs",
  },
  28609: {
    source: "Karazhan",
    boss: "Nightbane",
    phase: 1,
    slot: "neck",
  },
  28731: {
    source: "Karazhan",
    boss: "Netherspite",
    phase: 1,
    slot: "neck",
  },
  28752: {
    source: "Karazhan",
    boss: "Chess Event",
    phase: 1,
    slot: "feet",
  },
  28753: {
    source: "Karazhan",
    boss: "Chess Event",
    phase: 1,
    slot: "ring",
  },
  28763: {
    source: "Karazhan",
    boss: "Prince Malchezaar",
    phase: 1,
    slot: "ring",
  },
  28765: {
    source: "Karazhan",
    boss: "Prince Malchezaar",
    phase: 1,
    slot: "back",
  },
  28770: {
    source: "Karazhan",
    boss: "Prince Malchezaar",
    phase: 1,
    slot: "mainHand",
  },
  28771: {
    source: "Karazhan",
    boss: "Prince Malchezaar",
    phase: 1,
    slot: "mainHand",
  },
  28780: {
    source: "Magtheridon's Lair",
    boss: "Magtheridon",
    phase: 1,
    slot: "hands",
  },
  28790: {
    quest: 11002,
    source: "Quests",
    phase: 1,
    slot: "ring",
  },
  28793: {
    quest: 11002,
    source: "Quests",
    phase: 1,
    slot: "ring",
  },
  28799: {
    source: "Gruul's Lair",
    boss: "High King Maulgar",
    phase: 1,
    slot: "waist",
  },
  28803: {
    source: "Gruul's Lair",
    boss: "Gruul the Dragonkiller",
    phase: 1,
    slot: "head",
  },
  28822: {
    source: "Gruul's Lair",
    boss: "Gruul",
    phase: 1,
    slot: "neck",
  },
  28878: {
    source: "The Aldor",
    phase: 1,
    slot: "shoulders",
  },
  28881: {
    source: "The Aldor",
    phase: 1,
    slot: "shoulders",
  },
  28886: {
    source: "The Aldor",
    phase: 1,
    slot: "shoulders",
  },
  28887: {
    source: "The Aldor",
    phase: 1,
    slot: "shoulders",
  },
  29086: {
    subItem: 29761,
    source: "Karazhan",
    boss: "Prince Malchezaar",
    phase: 1,
    slot: "head",
  },
  29087: {
    subItem: 29753,
    source: "Magtheridon's Lair",
    boss: "Magtheridon",
    phase: 1,
    slot: "chest",
  },
  29172: {
    source: "Cenarion Expedition",
    phase: 1,
    slot: "ring",
  },
  29189: {
    source: "Honor Hold",
    phase: 1,
    slot: "head",
  },
  29191: {
    source: "The Sha'tar",
    phase: 1,
    slot: "head",
  },
  29272: {
    source: "Badges of Justice",
    cost: 25,
    phase: 1,
    slot: "offHand",
  },
  29274: {
    cost: 25,
    source: "Badges of Justice",
    phase: 1,
    slot: "offHand",
  },
  29290: {
    quest: 10726,
    source: "Quests",
    phase: 1,
    slot: "ring",
  },
  29303: {
    source: "Scale of the Sands",
    phase: 3,
    slot: "ring",
  },
  29304: {
    source: "Scale of the Sands",
    phase: 3,
    slot: "ring",
  },
  29305: {
    source: "Scale of the Sands",
    phase: 3,
    slot: "ring",
  },
  29306: {
    source: "Scale of the Sands",
    phase: 3,
    slot: "ring",
  },
  29308: {
    source: "Scale of the Sands",
    phase: 3,
    slot: "ring",
  },
  29309: {
    source: "Scale of the Sands",
    phase: 3,
    slot: "ring",
  },
  29350: {
    source: "Heroic Underbog",
    boss: "The Black Stalker",
    phase: 1,
    slot: "wand",
  },
  29370: {
    source: "Badges of Justice",
    cost: 41,
    phase: 1,
    slot: "trinket",
  },
  29376: {
    cost: 41,
    source: "Badges of Justice",
    phase: 1,
    slot: "trinket",
  },
  29918: {
    source: "Tempest Keep",
    boss: "Al'ar",
    phase: 2,
    slot: "wrist",
  },
  29920: {
    source: "Tempest Keep",
    boss: "Al'ar",
    phase: 2,
    slot: "ring",
  },
  29922: {
    source: "Tempest Keep",
    boss: "Al'ar",
    phase: 2,
    slot: "ring",
  },
  29972: {
    source: "Tempest Keep",
    boss: "High Astromancer Solarian",
    phase: 3,
    slot: "legs",
  },
  29982: {
    source: "Tempest Keep",
    boss: "High Astromancer Solarian",
    phase: 2,
    slot: "wand",
  },
  29986: {
    source: "Tempest Keep",
    boss: "Void Reaver",
    phase: 3,
    slot: "head",
  },
  29989: {
    source: "Tempest Keep",
    boss: "Kael'thas Sunstrider",
    phase: 2,
    slot: "back",
  },
  29992: {
    source: "Tempest Keep",
    boss: "Kael'thas Sunstrider",
    phase: 2,
    slot: "back",
  },
  30018: {
    quest: 11007,
    source: "Quests",
    phase: 2,
    slot: "neck",
  },
  30036: {
    source: "Crafting",
    phase: 2,
    slot: "waist",
  },
  30038: {
    source: "Crafting",
    phase: 2,
    slot: "waist",
  },
  30062: {
    source: "SSC",
    boss: "The Lurker Below",
    phase: 2,
    slot: "wrist",
  },
  30092: {
    source: "SSC",
    boss: "Leotheras the Blind",
    phase: 2,
    slot: "feet",
  },
  30100: {
    source: "SSC",
    boss: "Fathom-Lord Karathress",
    phase: 2,
    slot: "feet",
  },
  30107: {
    source: "SSC",
    boss: "Lady Vashj",
    phase: 3,
    slot: "chest",
  },
  30108: {
    source: "SSC",
    boss: "Lady Vashj",
    phase: 2,
    slot: "mainHand",
  },
  30109: {
    source: "SSC",
    boss: "Lady Vashj",
    phase: 2,
    slot: "ring",
  },
  30110: {
    source: "SSC",
    boss: "Lady Vashj",
    phase: 2,
    slot: "ring",
  },
  30161: {
    subItem: 30243,
    source: "SSC",
    boss: "Lady Vashj",
    phase: 3,
    slot: "head",
  },
  30216: {
    subItem: 30237,
    source: "Tempest Keep",
    boss: "Kael'thas Sunstrider",
    phase: 2,
    slot: "chest",
  },
  30217: {
    subItem: 30240,
    source: "SSC",
    boss: "Leotheras the Blind",
    phase: 3,
    slot: "hands",
  },
  30219: {
    subItem: 30243,
    source: "SSC",
    boss: "Lady Vashj",
    phase: 2,
    slot: "head",
  },
  30220: {
    subItem: 30246,
    source: "SSC",
    boss: "Fathom-Lord Karathress",
    phase: 2,
    slot: "legs",
  },
  30221: {
    subItem: 30249,
    source: "Tempest Keep",
    boss: "Void Reaver",
    phase: 2,
    slot: "shoulders",
  },
  30377: {
    quest: 10323,
    source: "Quests",
    phase: 1,
    slot: "neck",
  },
  30666: {
    source: "Karazhan",
    phase: 1,
    slot: "neck",
  },
  30868: {
    source: "Hyjal Summit",
    boss: "Rage Winterchill",
    phase: 3,
    slot: "wrist",
  },
  30870: {
    source: "Hyjal Summit",
    boss: "Rage Winterchill",
    phase: 3,
    slot: "wrist",
  },
  30871: {
    source: "Hyjal Summit",
    boss: "Rage Winterchill",
    phase: 3,
    slot: "wrist",
  },
  30884: {
    source: "Hyjal Summit",
    boss: "Anetheron",
    phase: 3,
    slot: "shoulders",
  },
  30888: {
    source: "Hyjal Summit",
    boss: "Anetheron",
    phase: 3,
    slot: "waist",
  },
  30895: {
    source: "Hyjal Summit",
    boss: "Kaz'rogal",
    phase: 3,
    slot: "waist",
  },
  30911: {
    source: "Hyjal Summit",
    boss: "Archimonde",
    phase: 3,
    slot: "offHand",
  },
  30912: {
    source: "Hyjal Summit",
    boss: "Archimonde",
    phase: 3,
    slot: "legs",
  },
  30916: {
    source: "Hyjal Summit",
    boss: "Kaz'rogal",
    phase: 3,
    slot: "legs",
  },
  31032: {
    subItem: 31093,
    source: "Hyjal Summit",
    boss: "Azgalor",
    phase: 3,
    slot: "hands",
  },
  31037: {
    subItem: 31096,
    source: "Hyjal Summit",
    boss: "Archimonde",
    phase: 3,
    slot: "head",
  },
  31041: {
    subItem: 31090,
    source: "Black Temple",
    boss: "Illidan Stormrage",
    phase: 3,
    slot: "chest",
  },
  31045: {
    subItem: 31099,
    source: "Black Temple",
    boss: "The Illidari Council",
    phase: 3,
    slot: "legs",
  },
  31047: {
    subItem: 31102,
    source: "Black Temple",
    boss: "Mother Shahraz",
    phase: 3,
    slot: "shoulders",
  },
  31061: {
    subItem: 31092,
    source: "Hyjal Summit",
    boss: "Azgalor",
    phase: 3,
    slot: "hands",
  },
  31064: {
    subItem: 31097,
    source: "Hyjal Summit",
    boss: "Archimonde",
    phase: 3,
    slot: "head",
  },
  31065: {
    subItem: 31089,
    source: "Black Temple",
    boss: "Illidan Stormrage",
    phase: 3,
    slot: "chest",
  },
  31070: {
    subItem: 31101,
    source: "Black Temple",
    boss: "Mother Shahraz",
    phase: 3,
    slot: "shoulders",
  },
  31383: {
    quest: 10781,
    source: "Quests",
    phase: 1,
    slot: "ring",
  },
  31856: {
    quest: 10938,
    source: "Quests",
    phase: 3,
    slot: "trinket",
  },
  32237: {
    source: "Black Temple",
    boss: "High Warlord Naj'entus",
    phase: 3,
    slot: "mainHand",
  },
  32238: {
    source: "Black Temple",
    boss: "High Warlord Naj'entus",
    phase: 3,
    slot: "ring",
  },
  32239: {
    source: "Black Temple",
    boss: "High Warlord Naj'entus",
    phase: 3,
    slot: "feet",
  },
  32247: {
    source: "Black Temple",
    boss: "High Warlord Naj'entus",
    phase: 3,
    slot: "ring",
  },
  32256: {
    source: "Black Temple",
    boss: "Supremus",
    phase: 3,
    slot: "waist",
  },
  32270: {
    source: "Black Temple",
    boss: "Shade of Akama",
    phase: 3,
    slot: "wrist",
  },
  32271: {
    source: "Black Temple",
    boss: "Shade of Akama",
    phase: 3,
    slot: "legs",
  },
  32328: {
    source: "Black Temple",
    boss: "Teron Gorefiend",
    phase: 3,
    slot: "hands",
  },
  32329: {
    source: "Black Temple",
    boss: "Teron Gorefiend",
    phase: 3,
    slot: "head",
  },
  32337: {
    source: "Black Temple",
    boss: "Gurtogg Bloodboil",
    phase: 3,
    slot: "back",
  },
  32339: {
    source: "Black Temple",
    boss: "Gurtogg Bloodboil",
    phase: 3,
    slot: "waist",
  },
  32343: {
    source: "Black Temple",
    boss: "Gurtogg Bloodboil",
    phase: 3,
    slot: "wand",
  },
  32353: {
    source: "Black Temple",
    boss: "Reliquary of the Lost",
    phase: 3,
    slot: "hands",
  },
  32367: {
    source: "Black Temple",
    boss: "Mother Shahraz",
    phase: 3,
    slot: "legs",
  },
  32370: {
    source: "Black Temple",
    boss: "Mother Shahraz",
    phase: 3,
    slot: "neck",
  },
  32374: {
    source: "Black Temple",
    boss: "Illidan Stormrage",
    phase: 3,
    slot: "twoHand",
  },
  32483: {
    source: "Black Temple",
    boss: "Illidan Stormrage",
    phase: 3,
    slot: "trinket",
  },
  32496: {
    source: "Black Temple",
    boss: "Illidan Stormrage",
    phase: 3,
    slot: "trinket",
  },
  32500: {
    source: "Black Temple",
    boss: "Illidan Stormrage",
    phase: 3,
    slot: "mainHand",
  },
  32513: {
    source: "Black Temple",
    boss: "Shade of Akama",
    phase: 3,
    slot: "wrist",
  },
  32519: {
    source: "Black Temple",
    boss: "The Illidari Council",
    phase: 3,
    slot: "waist",
  },
  32524: {
    source: "Black Temple",
    boss: "Illidan Stormrage",
    phase: 3,
    slot: "back",
  },
  32525: {
    source: "Black Temple",
    boss: "Illidan Stormrage",
    phase: 3,
    slot: "head",
  },
  32527: {
    source: "Black Temple",
    phase: 3,
    slot: "ring",
  },
  32528: {
    source: "Black Temple",
    phase: 3,
    slot: "ring",
  },
  32584: {
    source: "Crafting",
    phase: 3,
    slot: "wrist",
  },
  32586: {
    source: "Crafting",
    phase: 3,
    slot: "wrist",
  },
  32587: {
    source: "Crafting",
    phase: 3,
    slot: "shoulders",
  },
  32590: {
    source: "Hyjal Summit",
    phase: 3,
    slot: "back",
  },
  32609: {
    source: "Hyjal Summit",
    phase: 3,
    slot: "feet",
  },
  32872: {
    quest: 11090,
    source: "Quests",
    phase: 3,
    slot: "wand",
  },
  33150: {
    source: "Enchanting",
    phase: 1,
    slot: "back",
  },
  33192: {
    source: "Badges of Justice",
    cost: 25,
    phase: 4,
    slot: "wand",
  },
  33281: {
    source: "Zul'Aman",
    boss: "Akil'zon",
    phase: 4,
    slot: "neck",
  },
  33283: {
    source: "Zul'Aman",
    boss: "Akil'zon",
    phase: 4,
    slot: "mainHand",
  },
  33285: {
    source: "Zul'Aman",
    boss: "Nalorakk",
    phase: 4,
    slot: "wrist",
  },
  33293: {
    source: "Zul'Aman",
    boss: "Akil'zon",
    phase: 4,
    slot: "ring",
  },
  33334: {
    source: "Badges of Justice",
    cost: 35,
    phase: 4,
    slot: "offHand",
  },
  33354: {
    source: "Zul'Aman",
    boss: "Jan'alai",
    phase: 4,
    slot: "mainHand",
  },
  33356: {
    source: "Zul'Aman",
    boss: "Jan'alai",
    phase: 4,
    slot: "head",
  },
  33357: {
    source: "Zul'Aman",
    boss: "Jan'alai",
    phase: 4,
    slot: "feet",
  },
  33463: {
    source: "Zul'Aman",
    boss: "Hex Lord Malacrass",
    phase: 4,
    slot: "head",
  },
  33466: {
    source: "Zul'Aman",
    boss: "Zul'jin",
    phase: 4,
    slot: "neck",
  },
  33468: {
    source: "Zul'Aman",
    boss: "Zul'jin",
    phase: 4,
    slot: "mainHand",
  },
  33471: {
    source: "Zul'Aman",
    boss: "Zul'jin",
    phase: 4,
    slot: "feet",
  },
  33483: {
    source: "Zul'Aman",
    phase: 4,
    slot: "waist",
  },
  33494: {
    source: "Zul'Aman",
    phase: 4,
    slot: "mainHand",
  },
  33497: {
    source: "Zul'Aman",
    phase: 4,
    slot: "ring",
  },
  33498: {
    source: "Zul'Aman",
    phase: 4,
    slot: "ring",
  },
  33584: {
    source: "Badges of Justice",
    cost: 75,
    phase: 4,
    slot: "legs",
  },
  33585: {
    source: "Badges of Justice",
    cost: 75,
    phase: 4,
    slot: "legs",
  },
  33586: {
    source: "Badges of Justice",
    cost: 60,
    phase: 4,
    slot: "hands",
  },
  33587: {
    source: "Badges of Justice",
    cost: 60,
    phase: 4,
    slot: "hands",
  },
  33588: {
    source: "Badges of Justice",
    cost: 35,
    phase: 4,
    slot: "wrist",
  },
  33592: {
    source: "Zul'Aman",
    boss: "Hex Lord Malacrass",
    phase: 4,
    slot: "back",
  },
  33829: {
    source: "Zul'Aman",
    boss: "Hex Lord Malacrass",
    phase: 4,
    slot: "trinket",
  },
  33922: {
    source: "PVP",
    phase: 3,
    slot: "neck",
  },
  34009: {
    source: "Hyjal Summit",
    phase: 3,
    slot: "mainHand",
  },
  34012: {
    source: "Black Temple",
    phase: 3,
    slot: "back",
  },
  34166: {
    source: "Sunwell Plateau",
    phase: 5,
    slot: "ring",
  },
  34170: {
    source: "Sunwell Plateau",
    boss: "Kalecgos",
    phase: 5,
    slot: "legs",
  },
  34176: {
    source: "Sunwell Plateau",
    boss: "Brutallus",
    phase: 5,
    slot: "mainHand",
  },
  34179: {
    source: "Sunwell Plateau",
    boss: "Brutallus",
    phase: 5,
    slot: "offHand",
  },
  34181: {
    source: "Sunwell Plateau",
    boss: "Brutallus",
    phase: 5,
    slot: "legs",
  },
  34182: {
    source: "Sunwell Plateau",
    boss: "Felmyst",
    phase: 5,
    slot: "twoHand",
  },
  34199: {
    source: "Sunwell Plateau",
    boss: "Lady Sacrolash",
    phase: 5,
    slot: "mainHand",
  },
  34202: {
    source: "Sunwell Plateau",
    boss: "Lady Sacrolash",
    phase: 5,
    slot: "shoulders",
  },
  34204: {
    source: "Sunwell Plateau",
    boss: "Lady Sacrolash",
    phase: 5,
    slot: "neck",
  },
  34205: {
    source: "Sunwell Plateau",
    boss: "Lady Sacrolash",
    phase: 5,
    slot: "back",
  },
  34206: {
    source: "Sunwell Plateau",
    boss: "Lady Sacrolash",
    phase: 5,
    slot: "offHand",
  },
  34209: {
    source: "Sunwell Plateau",
    boss: "Lady Sacrolash",
    phase: 5,
    slot: "shoulders",
  },
  34210: {
    source: "Sunwell Plateau",
    boss: "Lady Sacrolash",
    phase: 5,
    slot: "shoulders",
  },
  34212: {
    source: "Sunwell Plateau",
    boss: "M'uru",
    phase: 5,
    slot: "chest",
  },
  34230: {
    source: "Sunwell Plateau",
    boss: "M'uru",
    phase: 5,
    slot: "ring",
  },
  34232: {
    source: "Sunwell Plateau",
    boss: "M'uru",
    phase: 5,
    slot: "chest",
  },
  34233: {
    source: "Sunwell Plateau",
    boss: "M'uru",
    phase: 5,
    slot: "chest",
  },
  34242: {
    source: "Sunwell Plateau",
    boss: "Kil'jaeden",
    phase: 5,
    slot: "back",
  },
  34245: {
    source: "Sunwell Plateau",
    boss: "Kil'jaeden",
    phase: 5,
    slot: "head",
  },
  34335: {
    source: "Sunwell Plateau",
    boss: "Kil'jaeden",
    phase: 5,
    slot: "mainHand",
  },
  34336: {
    source: "Sunwell Plateau",
    boss: "Kil'jaeden",
    phase: 5,
    slot: "mainHand",
  },
  34337: {
    source: "Sunwell Plateau",
    boss: "Kil'jaeden",
    phase: 5,
    slot: "twoHand",
  },
  34339: {
    source: "Sunwell Plateau",
    boss: "Kil'jaeden",
    phase: 5,
    slot: "head",
  },
  34340: {
    source: "Sunwell Plateau",
    boss: "Kil'jaeden",
    phase: 5,
    slot: "head",
  },
  34342: {
    source: "Sunwell Plateau",
    boss: "Kil'jaeden",
    phase: 5,
    slot: "hands",
  },
  34344: {
    source: "Sunwell Plateau",
    boss: "Kil'jaeden",
    phase: 5,
    slot: "hands",
  },
  34347: {
    source: "Sunwell Plateau",
    phase: 5,
    slot: "wand",
  },
  34362: {
    source: "Crafting",
    phase: 5,
    slot: "ring",
  },
  34363: {
    source: "Crafting",
    phase: 5,
    slot: "ring",
  },
  34364: {
    source: "Crafting",
    phase: 5,
    slot: "chest",
  },
  34366: {
    source: "Crafting",
    phase: 5,
    slot: "hands",
  },
  34367: {
    source: "Crafting",
    phase: 5,
    slot: "hands",
  },
  34372: {
    source: "Crafting",
    phase: 5,
    slot: "hands",
  },
  34384: {
    subItem: 34169,
    source: "Sunwell Plateau",
    boss: "Kalecgos",
    phase: 5,
    slot: "legs",
  },
  34386: {
    subItem: 34170,
    source: "Sunwell Plateau",
    boss: "Kalecgos",
    phase: 5,
    slot: "legs",
  },
  34405: {
    subItem: 34339,
    source: "Sunwell Plateau",
    boss: "Kil'jaeden",
    phase: 5,
    slot: "head",
  },
  34434: {
    subItem: 34848,
    source: "Sunwell Plateau",
    boss: "Kalecgos",
    phase: 5,
    slot: "wrist",
  },
  34445: {
    subItem: 34852,
    source: "Sunwell Plateau",
    boss: "Kalecgos",
    phase: 5,
    slot: "wrist",
  },
  34528: {
    subItem: 34853,
    source: "Sunwell Plateau",
    boss: "Brutallus",
    phase: 5,
    slot: "waist",
  },
  34554: {
    subItem: 34855,
    source: "Sunwell Plateau",
    boss: "Brutallus",
    phase: 5,
    slot: "waist",
  },
  34563: {
    subItem: 34856,
    source: "Sunwell Plateau",
    boss: "Felmyst",
    phase: 5,
    slot: "feet",
  },
  34571: {
    subItem: 34858,
    source: "Sunwell Plateau",
    boss: "Felmyst",
    phase: 5,
    slot: "feet",
  },
  34895: {
    source: "Badges of Justice",
    cost: 150,
    phase: 5,
    slot: "mainHand",
  },
  34896: {
    source: "Badges of Justice",
    cost: 150,
    phase: 5,
    slot: "mainHand",
  },
  34901: {
    source: "Badges of Justice",
    cost: 75,
    phase: 5,
    slot: "legs",
  },
  34926: {
    source: "Badges of Justice",
    cost: 75,
    phase: 5,
    slot: "feet",
  },
  35431: {
    source: "Enchanting",
    phase: 1,
    slot: "chest",
  },
  38288: {
    source: "Brewfest",
    boss: "Coren Direbrew",
    phase: 1,
    slot: "trinket",
  },
  38290: {
    source: "Brewfest",
    boss: "Coren Direbrew",
    phase: 1,
    slot: "trinket",
  },
};
